name: Module CI/CD

on: 
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # # Npm install
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: npm ci
    #     
    #   
    # # Get the name from 'module.json'
    # - name: where am i
    #   shell: bash
    #   id: where-am-i
    #   run: ls -lha
    #   
    # # build
    # - name: Build the project
    #   shell: bash
    #   id: build
    #   run: node run build

    # Get the version from 'module.json'
    - name: Get Version
      shell: bash
      id: get-version
      run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

    # Get the name from 'module.json'
    - name: Get Includes
      shell: bash
      id: get-includes
      run: echo "::set-output name=files::$(node ./.github/workflows/get-includes.js)"

    # create a zip file with all files required by the module to add to the release
    - name: Zip Files
      working-directory: ./dist #SORRY BUT YOU HAVE TO USE DIST JUST LIKE GET OVER IT OR FIGURE OUT A BETTER WAY
      run: zip -r ../module.zip ${{steps.get-includes.outputs.files}}

    #Useful only for the template so we can leave the manifest and download urls empty
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_latest
      uses: microsoft/variable-substitution@v1
      with:
        files: './dist/module.json'
      env:
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/latest/download/module.zip

    - name: Initialize mandatory git config
      run: | 
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com

    - name: Commit manifest files
      id: make-commit
      run: | 
        git add ./dist/module.json
        git commit -m "feat: update placeholders"
        echo "::set-output name=commit::$(git rev-parse HEAD)"

    - name: Push the changes
      run: git push origin ${{github.ref}}

    # Update the 'latest' release
    - name: Update Latest Release
      id: create_latest_release
      uses: ncipollo/release-action@v1
      if: endsWith(github.ref, 'master')
      with:
        allowUpdates: true
        name: Latest
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './dist/module.json, ./module.zip'
        tag: latest
    
    # Create a release for this specific version
    - name: Create Version Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # set this to false if you want to prevent updating existing releases
        name: Release ${{ steps.get-version.outputs.version }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './dist/module.json,./module.zip'
        tag: ${{ steps.get-version.outputs.version }}
